<script setup>

</Script> 

<template>
    <div>

    </div>

</template>

<style scoped>
    div {
        max-width: 400px;
        margin: 0 auto;
        padding: 24px;
        border: 1px solid #ccc;
        border-radius: 8px;
    }
    h1 {
        text-align: center;
        margin-bottom: 16px;
    }
    form {
        display: flex;
        flex-direction: column;
    }
    input {
        margin-bottom: 12px;
        padding: 8px;
        font-size: 16px;
    }
    button {
        padding: 10px;
        font-size: 16px;
        background-color: #007BFF;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    button:hover {
        background-color: #0056b3;
    }
</style>